Step3-kakao-tech-campus/Team16_FE

package-lock.json
package.json
src/App.tsx
src/pages/DetailedPetPage.tsx
src/pages/Home.tsx

- react-router-dom 사용하여 라우터 설정해주었습니다.
- pages 디렉토리에 임시 페이지 만들어두었습니다.

feat: 라우터 설정, pages 디렉토리 및 하위 파일 생성

---

.eslintrc
src/App.tsx
src/components/atoms/RadarChart.tsx
src/components/atoms/StringWithLineBrake.tsx
src/components/molecules/DetailPetInfo.tsx
src/components/molecules/VDetailPetInfo.tsx
src/components/organisms/DetailPetData.tsx
src/components/organisms/VDetailPetData.tsx
src/pages/DetailPetPage.tsx

- interface를 camel case로 작성하던 것 수정
- for 반복문의 '++'를 '+= 1' 로 변경
- Dependency cycle 없애기 위하여 props들의 interface 선언 위치 변경
- 반응형 추가
- 변경된 api 명세에 맞게 interface, mock data, 페이지 레이아웃 등 변경(추후 다시 변경되어야 함)
- 전체적인 css 조정

fix: airbnb eslint 오류 해결

---

src/commons/CategoryModal.tsx
src/components/molecules/VDetailPetInfo.tsx
src/components/organisms/DetailPetData.tsx
src/components/organisms/VDetailPetData.tsx
src/layouts/GNB.tsx
src/pages/Home.tsx

- 백엔드 api가 완성되지 않아, 현재까지 정해진 응답 데이터를 기반으로 임시로 완성했습니다.
- GNB는 새로 이슈 발행해서, 새로운 브랜치에서 진행하겠습니다.

feat: api 제외 상세보기 페이지 완료

---

.env
.gitignore

- 그냥 삭제 후 commit만 하니까 그대로 남아있어서 해당 부분 찾아보고 해결했습니다. 
1. cache에서 .env 파일 삭제 후 commit and push
2. .env 파일 재생성
3. .gitignore에 .env 추가
4. commit and push

fix: 환경변수 파일 커밋으로 인한 문제 해결

---

README.md

파일 작성에서 남아 있던 부분 (페이지 기능 부분) 작성했습니다. 
목차의 블록 링크가 제대로 작동하지 않는 부분 수정했습니다.

docs: README.md 파일 수정

---

src/components/atoms/Input.tsx
src/components/molecules/InputGroup.tsx
src/components/organisms/VLoginInputForm.tsx
src/components/organisms/VSignupInputForm.tsx

#41 에 맞게 autocomplete 추가하였습니다.

feat: 로그인 / 회원가입 폼에 autocomplete 추가

---

src/components/organisms/DetailPetData.tsx
src/components/organisms/LoginInputForm.tsx
src/components/organisms/SignupInputForm.tsx
src/components/organisms/VSignupInputForm.tsx
src/recoil/registerState.ts

- API 주소 노출되는 문제 해결하기 위해 코드(주석 포함) 부분 수정했습니다. 
- 이거 add로 파일 지정해준다음에 commit . 하면 add하지 않았던 파일도 한꺼번에 push가 되나요...? 
fix 부분만 하려고 했는데 다른 파일도 push가 됐네요..

fix: 환경변수로 적용으로 인한 코드 내 API 주소 노출 수정 & feat: 회원가입 이메일 중복 확인 API 적용

---

src/layouts/VLargeGNB.tsx

- GNB의 링크 리스트에 hover 이펙트 추가했습니다.
- 로그인과 회원가입 버튼에 hover 이펙트 추가했습니다.
- X
- 로그인과 회원가입 버튼에 추가한 hover 이펙트가 마음에 들어서, 유사한 모양의 버튼에 전부 적용해도 좋을 것 같습니다.
- 비슷하게 생긴 회원가입 버튼, 등록완료 버튼이 가까이 있어서 어색해보입니다... 흠~

feat: 로그인 / 회원가입과 리스트에 hover 이펙트 추가

---

public/index.html
src/App.tsx
src/components/atoms/DetailRadio.tsx
src/components/molecules/Map.tsx
src/components/molecules/RadioGroup.tsx
src/components/molecules/VProfileCard.tsx
src/components/organisms/VNewList.tsx
src/components/organisms/VPagenation.tsx
src/components/organisms/VProfileListHome.tsx
src/components/organisms/VUrgentList.tsx
src/pages/MapPage.tsx
src/pages/NewListPage.tsx
src/pages/ProfileListPage.tsx
src/pages/RegisterPage.tsx
src/pages/ShelterInfoPage.tsx
src/pages/UrgentListPage.tsx

- 지도 api 등록 및 띄우기
- GNB 추가
- 지도 키워드로 검색
- 기타 ui 수정
- 카카오 api key값을 환경변수로 설정하는 게 좋을까요? 아님 이대로 쓰고 크램폴린 올릴 때 해도 충분하겠죠?

feat: 지도 등록 및 페이지 ui 수정

---

src/components/organisms/MRegisterForm.tsx

- Object.values(petInfo)에서 petInfo.isComplete는 검사하지 않도록 변경
- handleChange 메소드 내에서 최신 값을 사용
- 서버로 데이터 전송하는 부분 삭제
- X
- 아무래도 수미님 코드를 바꾼 거라, 보고 괜찮은 것 같다면 머지해주세요~

fix: 폼을 전부 채워도 allFieldsFilled가 false로 나타나는 오류 해결

---

public/index.html
src/pages/map/Map.tsx

- 검색된 데이터 배열에 담기 ( 나중에 백엔드에게 보내줘야하니까)
- 마커 이미지 커스텀 (임의로 구현함)
- 특정 보호소의 마커 이미지는 다르게 (코멘트 달겠습니다).
- 현재 위치 확인
- 현재 위치에서 가까운 곳만 표시
- 리스트 구현(시험 끝나고)
- 백엔드와 연동
- X

feat: 지도 구현

---

src/pages/register/RegisterHeader.tsx

- #80 이후에 feat -> develop -> main까지 동기화가 잘 되는지 확인해보기 위해 주석만 변경했습니다.
- X
- X

style: 브랜치 테스트 위해 주석 변경

---

src/commons/modals/RegisterModal.tsx
src/pages/detailPet/VDetailPetInfo.tsx
src/pages/register/RegisterHeader.tsx

- #85 에 나와있는 문제 해결
- 상세보기 페이지의 동물 상세정보 너비, 높이 증가
- headers에 JWT 넣어주기
- 등록하기 페이지에서 입력값에 대한 validation check
- X

feat: 등록하기 버튼 및 모달 오류 수정

---

.github/workflows/build-deploy.yml

actions workflow 파일을 추가했습니다.
develop branch에 PR이 발생했을 경우,
GitHub에서 제공하는 ubuntu에서 `npm build`를 실행해보고,
마지막으로 배포 URL을 호출하는 구성입니다.
Close #82

GitHub Actions workflow로 npm build, jenkins deploy endpoint 호출

---

src/pages/detailPet/VDetailPetData.tsx
src/pages/detailPet/VDetailPetInfo.tsx

- 이름, 상세정보 너비 설정
- 분양지역 높이 삭제
- X
- X

fix: 상세조회 페이지 잘림 현상 해결

---

src/pages/map/Map.tsx

- 현재 위치 설정 안 해도 지도 뜨도록 수정
- 백엔드에서 환경변수 제대로 설정해줘서 이번 배포로 확인 가능
- 카카오 api key값을 제가 관리하는게 더 편하겠다는 생각이 들어요

feat: 현재 위치 설정 안 해도 지도 뜨도록 변경

---

src/pages/map/Map.tsx

- 5번 중에 4번 꼴로 정상작동함
- 완전한 작동
- 불필요한 랜더링이 매우 많음
- 제가 해봤던 구현 중에 제일 어렵습니다.. 제가 더 붙잡고 있는다고 할 수 없을 것 같아요. 다른 분의 도움이 절실합니다.

fix: api와 통신한대로 안 보이던 것 일부 고침

---

src/commons/MonthDays.tsx
src/pages/register/Calendar.tsx
src/pages/register/VDayModalInput.tsx

- 백엔드와 통신을 위해 날짜 구조를 `yyyy-m-d` 구조에서 `yyyy-mm-dd` 구조로 수정했습니다.
resolved #94

fix: 날짜 출력 형식 변경

---

src/pages/register/RegisterHeader.tsx

feat: JWT 사용하여 등록하기 버튼 완성

---

src/pages/detailPet/VDetailPetData.tsx
src/pages/detailPet/VDetailPetInfo.tsx
src/pages/map/Map.tsx

백엔드에서 주는 나이 데이터가 변경돼서 (기존에는 2022년11월 같은 데이터) width를 줄여서 ui 완성할 수 있었습니다~

상세보기 페이지 ui 변경

---

src/pages/register/DetailRadio.tsx
src/pages/register/RadioGroup.tsx

- 라디오 버튼에서 isComplete 체크
- MRegisterForm에서 tempInfo가 최신 값을 가져오지 못하는 상태

fix: 등록하기 페이지 라디오 버튼 클릭 시 isComplete 체크 안 함 문제 해결

---

src/pages/register/DetailRadio.tsx
src/pages/register/MRegisterForm.tsx
src/pages/register/RadioGroup.tsx
src/pages/register/VMRegisterForm.tsx
src/pages/register/VRadioGroup.tsx
src/pages/update/UpdatePage.tsx
src/pages/update/UpdateRegisterForm.tsx

- 현재 값은 업데이트 되지만 isComplete 연산이 그 전에 끝나 업데이트 되지 않는 상황입니다.

fix: 등록하기 페이지 라디오 버튼 업데이트 문제 해결중

---

src/pages/login/LoginInputForm.tsx
src/pages/register/RegisterHeader.tsx

- 이메일 validate check 과정에서 최신값 사용하도록 했습니다.

fix: 이메일 형식 오류 해결

---

src/pages/register/RadioGroup.tsx
src/pages/register/RegisterHeader.tsx

fix: 라디오버튼에서 isComplete 확인하게 변경

---

src/pages/update/UpdateInput.tsx
src/pages/update/UpdateInputGroup.tsx
src/pages/update/UpdatePage.tsx
src/pages/update/UpdateRegisterForm.tsx
src/pages/update/VUpdateRegisterForm.tsx

- petInfo 받아와서 placeholder에다 넣어두기
- 받아온 petInfo를 고정으로 둬서 placeholder값이 변하지 않게 만들기
- value값에 넣어두어 지우고 다시쓰게 만들어야할지 고민

featL 수정하기 상세 페이지 구현

---

src/commons/ErrorBoundary.tsx
src/commons/modals/RegisterModal.tsx
src/pages/register/RegisterHeader.tsx
src/pages/update/UpdateHeader.tsx
src/pages/update/UpdatePage.tsx
src/pages/update/UpdateTemplate.tsx

- Suspense 사용을 위해 기존 `UpdatePage.tsx`에 있던 로직 부분을 template 단으로 내렸습니다.
- Suspense 사용을 위해 useQuery의 suspense 옵션을 true로 지정해주었습니다.
- 눈에 잘 보여야 확인이 쉬울 것 같아, 튀는 컴포넌트로 fallback에 설정해두었습니다. 추후 스켈레톤 만들어서 변경하면 됩니다.
- 에러바운더리 설정
- fallback props 추가
- 스켈레톤
- 예쁜 에러 페이지
- X

feat: 수정하기 페이지 완성

---

src/commons/SelectBox.tsx
src/pages/profileList/VProfileCard.tsx
src/pages/profileList/VProfileListHome.tsx
src/pages/profileList/newList/VNewList.tsx
src/pages/profileList/urgentList/VUrgentList.tsx
src/pages/register/VMRegisterForm.tsx
src/pages/register/VRadioGroup.tsx
src/pages/update/UpdateInput.tsx
src/pages/update/UpdateInputGroup.tsx
src/pages/update/VUpdateRegisterForm.tsx

#122
- 수정하기 defaultValue 추가
- 등록/수정하기 age 값 selectBox로 받아오게 수정
- 몸무게 양수만 입력되도록 수정
- 등록/수정하기 페이지 필수표시 
- 프로필리스트, 보호소 프로필 api 연결

fix: 등록/수정하기 age 박스 수정, ui 수정, 몸무게 인풋값 수정 

---

package.json
src/commons/LogoButton.tsx
src/commons/cookie/getUser.ts
src/layouts/VGNB.tsx
src/layouts/VLargeGNB.tsx
src/pages/login/LoginInputForm.tsx
src/pages/login/VLoginInputForm.tsx
src/pages/login/VLoginPage.tsx
src/pages/register/StatusScore.tsx
src/pages/register/StatusSelectGroup.tsx
src/pages/signUp/VSignupInputForm.tsx
src/pages/signUp/VSignupPage.tsx

- 특성 점수 컴포넌트
- 특성 이름 한글로 변경
- 컴포넌트 반응형 UI 추가
- 로그인, 회원가입 페이지
- 홈 화면으로 갈 수 있는 버튼 추가
- 상단 텍스트 반응형 UI 수정
- 하단 로그인, 회원가입 이동 버튼의 span 텍스트 button 텍스트로 이동
- 코드 리뷰 내용 반영
- 로그인 페이지 에러텍스트 컴포넌트로 분리
- 로그인 페이지 onSubmit 내 로직들 함수로 분리
- GNB removeUser -> removeToken으로 변수명 수정

Style: 특성 점수 컴포넌트 UI 변경 / 로그인, 회원가입 페이지 반응형 추가

---

src/App.tsx
src/pages/home/Home.tsx
src/pages/home/HomePage.tsx
src/pages/home/VHome.tsx

- 비디오 화면에 띄우기
- 숏폼 방식 화면배치
- 영상 크기 맞추기
- 기타 화면 ui

feat: 홈 api 연결 및 비디오 재생 여부 확인

---

src/App.tsx

fix: shelter path 변경

---

src/pages/profileList/VProfileCard.tsx
src/pages/shelterInfo/ShelterInfo.tsx
src/pages/shelterInfo/VShelterInfo.tsx

- 보호소 프로필의 유기견 프로필리스트에서 프로필 이미지 url, age 추가하였습니다.
- ProfileCard ui 수정 -> 너비 높이 맞춤

feat: 보호소 프로필 api 수정에 따른 화면 수정, 프로필 카드 ui 수정

---

src/pages/profileList/ProfileListHomeSkeleton.tsx
src/pages/profileList/newList/NewListSkeleton.tsx
src/pages/profileList/urgentList/UrgentListSkeleton.tsx
src/pages/shelterInfo/VShelterInfo.tsx

- 보호소 프로필 로그인상태 확인
- 로그인하지 않았을 경우 생기는 오류 해결
- 프로필리스트 스켈레톤 수정

fix: 보호소 프로필 로그인상태 확인 추가

---

src/pages/login/LoginInputForm.tsx

fix: accountInfo 쿠키 등록

---

src/pages/editProfile/EditProfilePage.tsx
src/pages/editProfile/EditProfilePageSkeleton.tsx

- 스켈레톤 넣어서 로딩 시 보여주도록 했습니다. 
close #145

회원정보 수정 페이지 스켈레톤 구현

---

src/commons/apis/useFetch.tsx
src/pages/profileList/ProfileListHome.tsx
src/pages/profileList/newList/NewList.tsx
src/pages/profileList/urgentList/UrgentList.tsx
src/pages/shelterInfo/ShelterInfo.tsx
src/pages/shelterInfo/VShelterInfo.tsx
src/pages/update/UpdateTemplate.tsx

- commons에 useFetch 파일 생성하여 데이터 요청하는 부분 재사용

refactor: useFetch 파일 생성

---

src/commons/UserToggleBox.tsx
src/layouts/VGNB.tsx

- 작은 화면에서는 ToggleBox로 아이콘을 누르면 정보 변경, 보호소 이동, 로그아웃 탭이 나오도록 구현했습니다.

반응형에 따른 유저 정보 관리 컴포넌트 제작

---

package.json
src/commons/apis/useFetch.tsx
src/commons/apis/useGetFetch.ts
src/commons/apis/usePostFetch.ts
src/layouts/ValidateCheckLayout.tsx
src/pages/editProfile/EditProfilePage.tsx
src/pages/editProfile/EditProfilePageSkeleton.tsx
src/pages/editProfile/VEditProfilePage.tsx

- undefined 문제 해결
- skeleton border round 추가
- get, post(또는 put) 방식 custom hook 구현
closed #172

보호소 정보 수정 페이지 undefined 문제 해결 및 custom fetch hook 구현

---

src/App.tsx
src/layouts/GNB.tsx
src/layouts/VGNB.tsx
src/layouts/VLargeGNB.tsx
src/layouts/ValidateCheckLayout.tsx
src/pages/detailPet/DetailPetPage.tsx
src/pages/editProfile/VEditProfilePage.tsx
src/pages/home/HomePage.tsx
src/pages/map/MapPage.tsx
src/pages/profileList/ProfileListPage.tsx
src/pages/profileList/newList/NewListPage.tsx
src/pages/profileList/urgentList/UrgentListPage.tsx
src/pages/register/RegisterPage.tsx
src/pages/shelterInfo/ShelterInfoPage.tsx
src/pages/update/UpdatePage.tsx

- 레이아웃 관리 방식 변경
- GNB, VaildationCheckLayout을 상단에 두고, 하단에 페이지가 오도록 했습니다.

CreateBrowserRouter로 레이아웃 관리 방식 변경

---

Dockerfile

feat/#185 Dockerfile 생성

---

src/pages/map/components/Map.tsx
src/pages/map/components/MapList.tsx
src/pages/map/useMap.ts

- 맵 파일 로더 만들었습니다.
카카오맵 api 로딩이 간헐적으로 오래 걸리는 상황이 있어서 파악용 로더만 추가시켰습니다.
- x
- x

feat: 맵 로더 생성

---

src/layouts/VLargeGNB.tsx
src/pages/home/components/CategoryBar.tsx
src/pages/home/components/Home.tsx
src/pages/home/components/HomeNoData.tsx
src/pages/home/components/HomeSkeleton.tsx
src/pages/home/components/HomeVideo.tsx
src/pages/home/components/VideoDragBar.tsx
src/pages/home/components/VideoOverlay.tsx
src/pages/home/homeType.d.ts

- onClick을 동영상 overlay 되는 요소들 전체에 지정(이거 예전에 한 것 같은데 같은 문제가 다시 있었습니다)
- 로더 위치 조정
- 카테고리 필터 휴대폰에서 뭉개짐 문제 해결
- x
- 바로 머지 하겠습니다.

홈 요소 위치 조정

---

src/pages/home/components/HomeVideo.tsx

- 로더가 동영상에서 계속 보이는 문제 해결
- x
- x

로더가 동영상에서 계속 보이는 문제 해결

---

public/index.html
src/App.tsx
src/commons/apis/usePostFetch.ts
src/commons/modals/TextGuideModal.tsx
src/layouts/ErrorBoundary.tsx
src/layouts/VGNB.tsx
src/layouts/VLargeGNB.tsx
src/pages/editProfile/EditProfilePage.tsx
src/pages/editProfile/components/EditProfileTemplate.tsx
src/pages/editProfile/components/VEditProfileTemplate.tsx
src/pages/editProfile/editProfileType.d.ts
src/pages/login/components/LoginInputForm.tsx
src/pages/login/components/VLoginInputForm.tsx
src/pages/login/loginType.d.ts
src/pages/signUp/components/SignupGuideModal.tsx
src/pages/signUp/components/SignupInputForm.tsx
src/pages/signUp/components/VSignupInputForm.tsx
src/pages/signUp/signupType.d.ts

- 페이지 별 에러캐칭 넣었습니다.
- GNB 로그인 했을 때만 등록하기 보이게 했습니다. 
- meta 태그 image가 보이지 않아서 수정했습니다.

멘토링 내용 적용 - 에러캐칭, GNB 컨텐츠 노출 수정, meta og 속성 수정

---

src/App.tsx
src/layouts/ErrorBoundary.tsx
src/pages/detailPet/DetailPetPage.tsx
src/pages/detailPet/components/DetailPetData.tsx
src/pages/detailPet/components/VDetailPetInfo.tsx
src/pages/map/components/Loader.tsx
src/pages/map/components/Map.tsx
src/pages/map/components/MapList.tsx
src/pages/map/mapType.d.ts
src/pages/map/useMap.ts
src/pages/profileList/components/ProfileList.tsx

- 홈 스켈레톤 재생성
- 카카오맵 api 호출 단계에 따른 다른 로딩 화면 구현(카카오맵 api의 속도가 가변적이라 카카오맵 api의 작동에 맞춰 설계)
- x
- x

홈 스켈레톤 재생성, 카카오맵 로딩 상태 관리

---

src/pages/home/components/Home.tsx

- 깜빡하고 홈화면 에러 처리를 추가 안 했었습니다..
새롭게 추가한 상태입니다
- x

홈화면 500번 응답 처리 추가
